version: "3.5"
services:
  jmx:
    build:
      context: .
    image: jmx-test
    # environment:
    #   JAVA_OPTS: -Dcom.sun.management.jmxremote.port=6660 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - 6660:6660
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
